services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    BytesCommerce\EasyBlog\:
        resource: '../'
        exclude:
            - '../DependencyInjection/'
            - '../Entity/'
            - '../Enum/'
            - '../EasyBlogBundle.php'

    _instanceof:
        BytesCommerce\EasyBlog\Controller\Backend\AbstractCrudController:
            tags: ['easyadmin.controller']

    BytesCommerce\EasyBlog\Repository\PostRepositoryInterface:
        alias: 'BytesCommerce\EasyBlog\Repository\PostRepository'
        public: true

    BytesCommerce\EasyBlog\Repository\CategoryRepositoryInterface:
        alias: 'BytesCommerce\EasyBlog\Repository\CategoryRepository'
        public: true

    BytesCommerce\EasyBlog\Repository\FaqRepositoryInterface:
        alias: 'BytesCommerce\EasyBlog\Repository\FaqRepository'
        public: true
